[[plugins]]
package = "@netlify/plugin-lighthouse"

# optional, fails build when a category is below a threshold
[plugins.inputs.thresholds]
accessibility = 0.9
best-practices = 0.9
performance = 0.99
pwa = 0.3
seo = 0.9

# optional, deploy the lighthouse report to a path under your site
[plugins.inputs]
output_path = "reports/lighthouse.html"
